### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by Maria12S** [Maria12S/Portefolio1#1]
- [ ] css erreur 404
- [ ] mettre les liens entres les pages
- [ ] ajouter des ancres
- [ ] verifier le code
- [ ] verifier l'indentation
- [ ] mettre le cv
- [ ] modifier css contact page d'acceuil
- [ ] faire une branche
- [ ] changer les bordures
